/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kuis2;

/**
 *
 * @author Dewa Pradipta
 */
public class Kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form Kuis2
     */
    public Kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Prs = new javax.swing.JButton();
        Hpus = new javax.swing.JButton();
        klr = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        HA = new javax.swing.JTextPane();
        rang1 = new javax.swing.JTextField();
        rang2 = new javax.swing.JTextField();
        rang3 = new javax.swing.JTextField();
        rang4 = new javax.swing.JTextField();
        dis = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Pembayaran");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(153, 11, 102, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Harga Barang 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 68, 83, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Harga Barang 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 106, 83, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Harga Barang 3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 144, 83, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Harga Barang 4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 182, 83, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("DISKON");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 223, 43, 15);

        Prs.setText("Proses");
        Prs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrsActionPerformed(evt);
            }
        });
        getContentPane().add(Prs);
        Prs.setBounds(60, 256, 65, 23);

        Hpus.setText("Hapus");
        Hpus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HpusActionPerformed(evt);
            }
        });
        getContentPane().add(Hpus);
        Hpus.setBounds(143, 256, 63, 23);

        klr.setText("Keluar");
        klr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klrActionPerformed(evt);
            }
        });
        getContentPane().add(klr);
        klr.setBounds(224, 256, 63, 23);

        jScrollPane1.setViewportView(HA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 290, 285, 104);
        getContentPane().add(rang1);
        rang1.setBounds(131, 66, 184, 20);
        getContentPane().add(rang2);
        rang2.setBounds(131, 104, 184, 20);

        rang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rang3ActionPerformed(evt);
            }
        });
        getContentPane().add(rang3);
        rang3.setBounds(131, 142, 184, 20);

        rang4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rang4ActionPerformed(evt);
            }
        });
        getContentPane().add(rang4);
        rang4.setBounds(131, 180, 184, 20);
        getContentPane().add(dis);
        dis.setBounds(131, 218, 184, 20);

        setBounds(0, 0, 416, 444);
    }// </editor-fold>//GEN-END:initComponents

    private void rang3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rang3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rang3ActionPerformed

    private void rang4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rang4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rang4ActionPerformed

    private void PrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrsActionPerformed
        // TODO add your handling code here:
        int br1 = Integer.parseInt(rang1.getText());
        int br2 = Integer.parseInt(rang2.getText());
        int br3 = Integer.parseInt(rang3.getText());
        int br4 = Integer.parseInt(rang4.getText());
        int diskon = Integer.parseInt(dis.getText());
        int total1;
        int total;
        int harga;
        
        harga = br1+br2+br3+br4;
        if (diskon == 0){
            total = harga;     
        }
        else{
           total1 = harga*diskon/100;
           total = harga - total1;
           
        }
        HA.setText("Harga barang 1: "+br1+"\nHarga Barang 2:" +br2+"\nHarga Barang 3:" +br3+"\n"
                + "Harga Barang 4: " +br4+"\nDiskon :" +diskon+"\nTotal bayar:" +total);
    }//GEN-LAST:event_PrsActionPerformed

    private void HpusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HpusActionPerformed
        // TODO add your handling code here:
        HA.setText("");
        rang1.setText("");
        rang2.setText("");
        rang3.setText("");
        rang4.setText("");
        dis.setText("");
    }//GEN-LAST:event_HpusActionPerformed

    private void klrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klrActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_klrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane HA;
    private javax.swing.JButton Hpus;
    private javax.swing.JButton Prs;
    private javax.swing.JTextField dis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton klr;
    private javax.swing.JTextField rang1;
    private javax.swing.JTextField rang2;
    private javax.swing.JTextField rang3;
    private javax.swing.JTextField rang4;
    // End of variables declaration//GEN-END:variables
}
